### ISSUE TITLE
[BUG] Input Shaper Panel

### ISSUE THREAD

**Issue by RazorCopter** [Guilouz/KlipperScreen-Flsun-Super-Racer#2]
From control panel : Settings > Input Shaper view this error:

####################################################################################
2022-10-05 13:04:18,072 [menu.py:evaluate_enable()] - Template: '{{ printer.firmware_retraction }}'
2022-10-05 13:04:18,076 [menu.py:arrangeMenuItems()] - Evaluating item: config input_shaper
2022-10-05 13:04:18,077 [menu.py:evaluate_enable()] - Template: '{{ printer.input_shaper }}'
2022-10-05 13:04:18,081 [menu.py:arrangeMenuItems()] - Evaluating item: config save
2022-10-05 13:04:18,081 [menu.py:arrangeMenuItems()] - Evaluating item: config network
2022-10-05 13:04:18,082 [menu.py:arrangeMenuItems()] - Evaluating item: config settings
2022-10-05 13:04:18,083 [menu.py:arrangeMenuItems()] - Evaluating item: config system
2022-10-05 13:04:18,089 [screen.py:show_panel()] - Current panel hierarchy: ['main_panel', 'main_panel_config']
2022-10-05 13:04:18,833 [screen_panel.py:menu_item_clicked()] - ### Creating panel input_shaper : input_shaper {'name': "{{ gettext('Input Shaper') }}", 'icon': 'move', 'panel': 'input_shaper', 'method': False, 'confirm': False, 'enable': '{{ printer.input_shaper }}', 'params': {}}
2022-10-05 13:04:18,833 [screen.py:_load_panel()] - Loading panel: input_shaper
2022-10-05 13:04:18,834 [screen.py:_load_panel()] - Panel path: /home/pi/KlipperScreen/panels/input_shaper.py
2022-10-05 13:04:18,851 [screen.py:_load_panel()] - Unable to create panel input_shaper
ButtonImage() got an unexpected keyword argument 'lines'
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 308, in _load_panel
    return self.load_panel[panel](*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 12, in create_panel
    return InputShaperPanel(*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 28, in __init__
    self.calibrate_btn = self._gtk.ButtonImage("move", _('Finding ADXL'), "color1", lines=1)
TypeError: ButtonImage() got an unexpected keyword argument 'lines'
2022-10-05 13:04:18,855 [screen.py:show_panel()] - Unable to load panel input_shaper
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 308, in _load_panel
    return self.load_panel[panel](*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 12, in create_panel
    return InputShaperPanel(*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 28, in __init__
    self.calibrate_btn = self._gtk.ButtonImage("move", _('Finding ADXL'), "color1", lines=1)
TypeError: ButtonImage() got an unexpected keyword argument 'lines'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 317, in show_panel
    self.panels[panel_name] = self._load_panel(panel_type, self, title)
  File "/home/pi/KlipperScreen/screen.py", line 312, in _load_panel
    raise Exception(msg) from e
Exception: Unable to create panel input_shaper
ButtonImage() got an unexpected keyword argument 'lines'
2022-10-05 13:04:18,856 [screen.py:show_error_modal()] - Showing error modal: Unable to load panel input_shaper
Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 308, in _load_panel
    return self.load_panel[panel](*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 12, in create_panel
    return InputShaperPanel(*args)
  File "/home/pi/KlipperScreen/panels/input_shaper.py", line 28, in __init__
    self.calibrate_btn = self._gtk.ButtonImage("move", _('Finding ADXL'), "color1", lines=1)
TypeError: ButtonImage() got an unexpected keyword argument 'lines'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/KlipperScreen/screen.py", line 317, in show_panel
    self.panels[panel_name] = self._load_panel(panel_type, self, title)
  File "/home/pi/KlipperScreen/screen.py", line 312, in _load_panel
    raise Exception(msg) from e
Exception: Unable to create panel input_shaper
ButtonImage() got an unexpected keyword argument 'lines'
2022-10-05 13:06:22,753 [screen.py:_menu_go_back()] - #### Menu go back

####################################################################################

**Comment by Guilouz** [comment]
Not related to my version, issue is from sources of KlipperScreen.
